language: c
install:
  - curl -sfLO http://apertium.projectjj.com/apt/nightly/pool/main/h/hfst/hfst_3.15.0+g3702~c2f13c6e-1~trusty1_amd64.deb
  - curl -sfLO http://apertium.projectjj.com/apt/nightly/pool/main/h/hfst/libhfst52_3.15.0+g3702~c2f13c6e-1~trusty1_amd64.deb
  - sudo dpkg --install libhfst??_*.deb
  - sudo dpkg --install hfst_*.deb
script:
  - make fsts
